### ISSUE TITLE
Does not work with Phoenix 1.3

### ISSUE THREAD

**Issue by rhazdon** [sldab/mix_apidoc#5]
Hi Guys,

the path to apidoc is static and does not work for Phoenix 1.3.

**Comment by sldab** [comment]
Please read the documentation. It's possible to specify the path to the apidoc executable with the `apidoc_bin` config parameter.

There's no need to do this as of version 0.5.1. It autodetects Phoenix 1.3 projects and sets the defaults for `apidoc_bin` and `input_dir` accordingly

**Comment by rhazdon** [comment]
@sldab, thanks! :)
